### ISSUE TITLE
Currently can't see countdown

### ISSUE THREAD

**Issue by LordZarinthe** [afriestad/blarg#4]
So i know that you can't help with the bungie account side issue but i can't see the countdown anymore, not sure if im the only one experiencing it and i can't find a contact for for bungie for this at all.  i doubt you would be able to help but if its not just me having this issue i haven't seen anything on twitter about it.

thanks

**Comment by afriestad** [comment]
Hey!

This is a known issue. Since the website maintenance on Thursday last week, nobody has been able to access the countdown.

In the mean time, I have made a stand-in. We've notified Bungie multiple places, hopefully it will be fixed during next maintenance :)

Interim countdown: [https://afriestad.github.io/blarg/countdown](https://afriestad.github.io/blarg/countdown)

**Comment by LordZarinthe** [comment]
Thanks for the info, and yeah lets hope its fixed.  Have a good one.

**Comment by afriestad** [comment]
This was fixed in Bungie's end on Wednesday
